apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: create-ocp-namespace-swt
    sonataflow.org/workflow-app: create-ocp-namespace-swt
  name: create-ocp-namespace-swt-props
data:
  application.properties: |
    # Backstage Notifications service
    rhdh_url=${BACKSTAGE_BACKEND_URL}
    quarkus.rest-client.notifications.url=${rhdh_url}
    quarkus.openapi-generator.notifications.auth.BearerToken.bearer-token=${BACKSTAGE_BACKEND_BEARER_TOKEN}

    # Ticket Manager
    ticket_manager_url=${TICKET_MANAGER_URL}
    quarkus.rest-client.ticket_manager_openapi_yaml.url=${TICKET_MANAGER_URL}

    # Backstage Scaffolder service
    quarkus.rest-client.scaffolder_openapi_yaml.url=${rhdh_url}
    quarkus.openapi-generator.scaffolder_openapi_yaml.auth.BearerToken.bearer-token=${BACKSTAGE_BACKEND_BEARER_TOKEN}
    software_template_ref=${SOFTWARE_TEMPLATE_REF}

    # quarkus.tls.trust-all=true

    quarkus.log.category."org.apache.http".level=INFO
    quarkus.log.level=INFO

    quarkus.flyway.migrate-at-start=true
