apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: 01-create-ocp-namespace-swt-resources-schemas
data:
  create-ocp-namespace-swt-schema.json: |-
    {
      "$id": "classpath:/schemas/create-ocp-namespace-swt-schema.json",
      "title": "Workflow input data",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "namespace": {
          "title": "Namespace Name",
          "description": "OCP namespace to create",
          "type": "string",
          "pattern": "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
        },
        "requester": {
          "title": "Requester",
          "type": "string",
          "description": "The requester of the namespace",
          "pattern": "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
        }, 
        "reason": {
          "title": "Reason",
          "type": "string",
          "description": "The reason a large namespace is required"
        },    
        "recipients": {
          "title": "Recipients",
          "type": "array",
          "description": "A list of recipients for the notification in the format of 'user:<namespace>/<username>' or 'group:<namespace>/<groupname>', i.e. 'user:default/jsmith'",
          "items": {
            "title": "Recipient",
            "type": "string",
            "pattern": "^(user|group):[a-z0-9]([-a-z0-9]*[a-z0-9])?/([a-z0-9]([-a-z0-9]*[a-z0-9])?)$"
          },
          "minItems": 1
        }
      },
      "required": [
        "namespace",
        "requester",
        "reason",
        "recipients"
      ]
    }
  workflow-output-schema.json: |-
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "WorkflowResult",
      "description": "Schema of workflow output",
      "type": "object",
      "properties": {
        "result": {
          "type": "object",
          "properties": {
            "completedWith": {
              "description": "The state of workflow completion.",
              "type": "string",
              "enum": [
                "error",
                "success",
                "warning"
              ]
            },
            "message": {
              "description": "High-level summary of the current status, free-form text, human readable.",
              "type": "string"
            },
            "nextWorkflows": {
              "description": "List of workflows suggested to run next. Items at lower indexes are of higher priority.",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "description": "Workflow identifier",
                    "type": "string"
                  },
                  "name": {
                    "description": "Human readable title describing the workflow.",
                    "type": "string"
                  }
                },
                "required": [
                  "id",
                  "name"
                ]
              }
            },
            "outputs": {
              "description": "Additional structured output of workflow processing. This can contain identifiers of created resources, links to resources, logs or other output.",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "key": {
                    "description": "Unique identifier of the option. Preferably human-readable.",
                    "type": "string"
                  },
                  "value": {
                    "description": "Free form value of the option.",
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "number"
                      }
                    ]
                  },
                  "format": {
                    "description": "More detailed type of the 'value' property. Defaults to 'text'.",
                    "enum": [
                      "text",
                      "number",
                      "link"
                    ]
                  }
                },
                "required": [
                  "key",
                  "value"
                ]
              }
            }
          }
        }
      }
    }

