apiVersion: v1
data:
  create-ocp-namespace-schema.json: |-
    {
      "$id": "classpath:/schemas/create-ocp-namespace-schema.json",
      "title": "Workflow input data",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "namespace": {
          "title": "Namespace Name",
          "description": "OCP namespace to create",
          "type": "string",
          "pattern": "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
        },
        "openshiftUser": {
          "title": "OpenShift User Name",
          "description": "OpenShift username of requester",
          "type": "string",
          "pattern": "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
        },
        "recipients": {
          "title": "Recipients",
          "type": "array",
          "description": "A list of recipients for the notification in the format of 'user:<namespace>/<username>' or 'group:<namespace>/<groupname>', i.e. 'user:default/jsmith'",
          "items": {
            "title": "Recipient",
            "type": "string",
            "pattern": "^(user|group):[a-z0-9]([-a-z0-9]*[a-z0-9])?/([a-z0-9]([-a-z0-9]*[a-z0-9])?)$"
          },
          "minItems": 1
        }
      },
      "required": [
        "namespace",
        "recipients"
      ]
    }
  workflow-output-schema.json: |-
    {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "WorkflowResult",
        "description": "Schema of workflow output",
        "type": "object",
        "properties": {
            "result": {
                "$ref": "../shared/schemas/workflow-result-schema.json",
                "type": "object"
            }
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: 01-create-ocp-namespace-resources-schemas
