apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orchestrator-workflow-greeting
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    namespace: {{ orchestrator_namespace }}
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: https://{{ gitlab_host }}/rhdh/orchestrator-workflows.git
    path: charts/greeting
    targetRevision: main
    helm:
      values: |
        persistence:
          postgresql:
            secretRef:
              name: sonataflow-psql-postgresql
              userKey: database-user
              passwordKey: database-password
            serviceRef:
              name: sonataflow-psql-postgresql
              port: 5432
              databaseName: sonataflow
              databaseSchema: greeting

  syncPolicy:
    automated: {}