persistence:
  postgresql:
    secretRef:
      name: sonataflow-psql-postgresql
      userKey: database-user
      passwordKey: database-password
    serviceRef:
      name: sonataflow-psql-postgresql
      port: 5432
      databaseName: sonataflow
      databaseSchema: create-ocp-namespace

image: 
  repository: quay.io/redhat_pe_workshop/serverless-workflow-create-ocp-namespace
  tag: e200ba9

ticketManager:
  url:

secret:
  openshiftToken: orchestrator-ocp-token
  backstageToken: orchestrator-backstage-backend-token